version: "3"

services:
  ubuntu:
    build: .
    user: root
    stdin_open: true
    tty: true
    volumes:
      - ./tests:/home/selenium/tests
    links:
      - selenium 
      - novnc

  novnc:
    image: javanile/novnc
    environment:
      - REMOTE_HOST=localhost
      - REMOTE_PORT=5900
    ports:
      - "8081:8081"
    links:
      - selenium

  selenium:
    image: selenium/standalone-chrome:latest
    shm_size: 1g   # It was 64MB by default, which was causing the issue. Set memory to 100MB or more 
    mem_limit: 1g  # Set memory to 2 GB
    cpus: 2        # Set CPU usage to 2 cores
    environment:
      - VNC_NO_PASSWORD=1
      - SCREEN_WIDTH=1800
      - SCREEN_HEIGHT=960
    ports:
      - "4444:4444"
      - "5900:5900"
